version: "3.7"

services: 
  javascript:
    image: javascript-ssh-env:12
    build: 
      context: .
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    ports: 
      - "127.0.0.1:22227:22"
    networks: 
      - develop
    volumes: 
      - ~/.ssh/id_rsa.pub:/tmp/ssh_key.pub

networks:
  develop: