version: "3.7"

services: 
  cpp:
    image: cpp-ssh-env:8.3
    build: 
      context: .
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    ports: 
      - "127.0.0.1:22221:22"
    networks: 
      - develop
    volumes: 
      - ~/.ssh/id_rsa.pub:/tmp/ssh_key.pub

networks:
  develop: