version: "3.7"

services: 
  java:
    image: java-ssh-env:14
    build: 
      context: .
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    ports: 
      - "127.0.0.1:22223:22"
    networks: 
      - develop
    volumes: 
      - ~/.ssh/id_rsa.pub:/tmp/ssh_key.pub

networks:
  develop: