version: "3.7"

services: 
  go:
    image: go-ssh-env:1.14
    build: 
      context: .
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    environment: 
      - GOROOT=/usr/local/go
    ports: 
      - "127.0.0.1:22222:22"
    networks: 
      - develop
    volumes: 
      - ~/.ssh/id_rsa.pub:/tmp/ssh_key.pub

networks:
  develop: