version: "3.7"

services: 
  python:
    image: python-ssh-env:3.9
    build: 
      context: .
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    ports: 
      - "127.0.0.1:22225:22"
    networks: 
      - develop
    volumes: 
      - ~/.ssh/id_rsa.pub:/tmp/ssh_key.pub

networks:
  develop:
