version: "3.7"

services: 
  php:
    image: php-ssh-env:7.4
    build: 
      context: .
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    ports: 
      - "127.0.0.1:22224:22"
      - "127.0.0.1:8000:80"
    networks: 
      - develop
    volumes: 
      - ~/.ssh/id_ed25519.pub:/tmp/ssh_key.pub

networks:
  develop: